name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.26.x"

      - uses: lovasoa/setup-emscripten@master
        with:
          emscripten-version: "1.38.47"

      - name: install wabt
        uses: chiefbiiko/setup-wabt@1.0.0
        run: wat2wasm --help

      - run: make all debug=true
      - run: make package
      - run: make app

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    defaults:
      run:
        working-directory: higan/out/package
